In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])

In [10]:
Result = arr ** 2 #vectrized operation

In [11]:
Result

array([ 1,  4,  9, 16, 25])

In [12]:
Result1 = arr + 10

In [13]:
Result1

array([11, 12, 13, 14, 15])

In [17]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [18]:
arr2 = np.array([11, 22, 33])

In [19]:
result = arr1 + arr2

In [20]:
result

array([[12, 24, 36],
       [15, 27, 39]])