In [1]:
import numpy as np

In [8]:
arr = np.array([12, 4, 23, 12])

In [9]:
arr.dtype

dtype('int64')

In [10]:
arr.astype("float64")

array([12.,  4., 23., 12.])

In [12]:
arr2 = np.array([12, 4, 23, 12], dtype = "float32" )

In [13]:
arr2

array([12.,  4., 23., 12.], dtype=float32)

In [16]:
arr2.nbytes

16

In [17]:
arr.nbytes

32

## Normalization

In [18]:
data = np.array([[10, 15, 20], [25, 30, 35], [40, 45, 50], [55, 60, 65], [15, 25, 35]])

In [20]:
mean = data.mean(axis=0)
std = data.std(axis=0)
normalized_data = (data - mean) / std

In [21]:
normalized_data

array([[-1.14783198, -1.26491106, -1.37281295],
       [-0.24164884, -0.31622777, -0.39223227],
       [ 0.6645343 ,  0.63245553,  0.58834841],
       [ 1.57071744,  1.58113883,  1.56892908],
       [-0.84577093, -0.63245553, -0.39223227]])