In [3]:
import numpy as np

## Indexing ##

In [7]:
arr = np.array([10, 20, 30, 40])

In [8]:
print(arr[0])  # 10

10


In [9]:
print(arr[-1]) # 40

40


## Slicing ##

In [10]:
arr = np.array([10, 20, 30, 40, 50])

In [11]:
print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)

[20 30 40]


In [12]:
print(arr[:3])   # [10 20 30] (first 3 elements)

[10 20 30]


In [13]:
print(arr[::2])  # [10 30 50] (every 2nd element)

[10 30 50]


In [14]:
sliced = arr[1:4]

In [15]:
sliced[0] = 999

In [16]:
print(arr) 

[ 10 999  30  40  50]


## Fancy Indexing & Boolean Masking ##

### Fancy Indexing (Select Multiple Elements)

In [17]:
arr = np.array([10, 20, 30, 40, 50])

In [18]:
idx = [0, 2, 4]  # Indices to select

In [19]:
print(arr[idx])  # [10 30 50]

[10 30 50]


### Boolean Masking (Filter Data)

In [20]:
arr = np.array([10, 20, 30, 40, 50])

In [21]:
mask = arr > 25  # Condition: values greater than 25

In [22]:
print(arr[mask]) 

[30 40 50]
