In [2]:
import numpy as np

In [3]:
arr = np.array([2, 3, 5, 7, 10])

In [4]:
np.mean(arr)

np.float64(5.4)

In [5]:
np.max(arr)

np.int64(10)

In [6]:
np.min(arr)

np.int64(2)

In [7]:
np.std(arr)

np.float64(2.870540018881465)

In [8]:
np.var(arr)

np.float64(8.24)

In [9]:
np.sum(arr)

np.int64(27)

In [10]:
np.prod(arr)

np.int64(2100)

In [11]:
np.median(arr)

np.float64(5.0)

In [13]:
np.percentile(arr, 75)

np.float64(7.0)

In [14]:
np.argmin(arr) #smallest element index inside the array

np.int64(0)

In [16]:
np.argmax(arr) #largest element index inside the array

np.int64(4)

In [20]:
arr2 = np.array([2, 3, 5, 17, 60, 2, 17, 3])

In [21]:
np.unique(arr2)

array([ 2,  3,  5, 17, 60])

In [25]:
np.diff(arr2)

array([  1,   2,  12,  43, -58,  15, -14])

In [26]:
np.cumsum(arr2)

array([  2,   5,  10,  27,  87,  89, 106, 109])

In [28]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [29]:
np.log(arr2)

array([0.69314718, 1.09861229, 1.60943791, 2.83321334, 4.09434456,
       0.69314718, 2.83321334, 1.09861229])

In [31]:
np.exp(arr2)

array([7.38905610e+00, 2.00855369e+01, 1.48413159e+02, 2.41549528e+07,
       1.14200739e+26, 7.38905610e+00, 2.41549528e+07, 2.00855369e+01])