### Understanding Axes in NumPy

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

In [3]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(np.sum(arr, axis=0))  # Sum along rows (down each column)

[12 15 18]


In [5]:
print(np.sum(arr, axis=1))  # Sum along columns (across each row)

[ 6 15 24]


### Indexing in Multidimensional Arrays

In [6]:
print(arr[1, 2])  # Row index 1, Column index 2

6


In [8]:
print(arr[2, 1])

8


In [9]:
print(arr[0:2, 1:3])  # Extracts first 2 rows and last 2 columns

[[2 3]
 [5 6]]


###  Indexing in 3D Arrays

In [10]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

In [11]:
print(arr3D[0, 1, 2])

6


In [12]:
print(arr3D[:, 0, :])   # Get the first row from both sheets

[[1 2 3]
 [7 8 9]]


 ## Practical Example: Selecting Data Along Axes

In [18]:
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)  # Output: [1 4 7]

[1 4 7]


In [19]:
# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

[[1 2 3]
 [7 8 9]]


## Changing Data Along an Axis

In [20]:
# Replace all elements in column 1 with 0
arr[:, 1] = 0

In [21]:
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
