In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])  # 1D array

In [3]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
print(arr1)  

[1 2 3 4 5]


In [6]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [10]:
np.zeros((3, 3))    # 3x3 array of zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2, 4))     # 2x4 array of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.full((2, 2), 7)  # 2x2 array filled with 7

array([[7, 7],
       [7, 7]])

In [13]:
np.eye(4)           # 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.arange(1, 10, 2) # [1, 3, 5, 7, 9] (like range)

array([1, 3, 5, 7, 9])

In [15]:
np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

 ## Checking Array Properties ##

In [16]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

In [17]:
print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns

Shape: (2, 3)


In [18]:
print("Size:", arr.size)     # 6 → total elements

Size: 6


In [19]:
print("Dimensions:", arr.ndim) # 2 → 2D array

Dimensions: 2


In [20]:
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Data type: int64


##  Changing Data Types ##

In [21]:
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type

In [22]:
print(arr.dtype)  # float32

float32


In [23]:
arr_int = arr.astype(np.int32)  # Convert float to int

In [24]:
print(arr_int)  # [1 2 3]

[1 2 3]


## Reshaping and Flattening Arrays ##

In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [26]:
print(arr.shape)  # (2, 3)

(2, 3)


In [27]:
reshaped = arr.reshape((3, 2))  # Change shape

In [28]:
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [29]:
flattened = arr.flatten()  # Convert 2D → 1D

In [30]:
print(flattened)  # [1 2 3 4 5 6]

[1 2 3 4 5 6]
